### ISSUE TITLE
Requires win sound module?

### ISSUE THREAD

**Issue by 2600box** [elevul/telegram-link-opener#1]
It seems you have required win sound module? I had to comment this out. Would be great to have an alternative or clarify this in the docs. Cheers

**Comment by elevul** [comment]
Hi, that appears to indeed be the case since this was made for Windows, but the winsound module is normally already integrated in all python installs, no?

**Comment by 2600box** [comment]
I don't use windows. I have tested and your script works well on macos, just have to comment the winsound. if you wanted to make it cross platform, I think you could replace with https://pypi.org/project/playsound/

**Comment by elevul** [comment]
Hi,

Implemented. As I don't have a Mac, can you please test and validate?

**Comment by 2600box** [comment]
Works great, plays the sound after installing pyobj and playsound modules with pip3. Cheers

**Comment by elevul** [comment]
Thank you for the confirmation
